FROM python:3.10-slim

# Install dependencies yang dbt-athena perlukan
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Install dbt-athena 
RUN pip install --no-cache-dir dbt-athena-community

WORKDIR /usr/app